name: nf-wrap CI
# This workflow runs wrappers with minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

env:
  NXF_ANSI_LOG: false

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  changes:
    name: Check for changes
    runs-on: ubuntu-latest
    outputs:
      # Expose matched filters as job 'wrap' output variable
      wrap: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: "tests/config/tags.yml"
  test:
    runs-on: ubuntu-20.04

    name: ${{ matrix.tags }} ${{ matrix.profile }}
    needs: changes
    if: needs.changes.outputs.wrap != '[]'
    strategy:
      fail-fast: false
      matrix:
        tags: ["${{ fromJson(needs.changes.outputs.wrap) }}"]
        profile: ["docker", "singularity", "conda"]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Install nf-test
        run: |
          wget -qO- https://code.askimed.com/install/nf-test | bash
          sudo mv nf-test /usr/local/bin/

      - name: Set up Singularity
        if: matrix.profile == 'singularity'
        uses: eWaterCycle/setup-singularity@v5
        with:
          singularity-version: 3.7.1

      - name: Set up miniconda
        if: matrix.profile == 'conda'
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge,bioconda,defaults
          python-version: ${{ matrix.python-version }}

      - name: Conda clean
        if: matrix.profile == 'conda'
        run: conda clean -a

      - name: Run nf-test
        run: |
          nf-test test \
            --profile=laptop,${{ matrix.profile }} \
            tests/tools/${{ matrix.tags }}/*.nf.test \
            --tap=test.tap

      - uses: pcolby/tap-summary@v1
        with:
          path: >-
            test.tap
